# -*- coding: utf-8 -*-
"""artificial intelligence

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUCHzVBFpAdz8ZJV9yBDpl3zaFP_CtEU
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

# Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")

# Sample product review (you can change only this text later)
review = """The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs chargimg often.
The fan makes noise when many apps are running.
Overall, it is a good laptop for students but not for gaming.
"""
# Split review into sentences
sentences = review.split(".")


pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
         continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)


    elif result["label"] == "NEGATIVE":
        cons.append(s)
# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

# Create table
df = pd.DataFrame({
     "Pros": pros,
     "Cons": cons
})

df

!pip install sentence-transformers



from sentence_transformers import SentenceTransformer ,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter text1 : ")
text2 = input("Enter text2 : ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1, embedding2)
print("\nSimilarity Score:",round(float(similarity),2))
if similarity > 0.75:
   print("Similarity Level: High")
elif similarity > 0.4:
   print("Similarity Level: Medium")
else:
   print("Similarity Level: Low")

!pip install transforms torch

from transformers import pipeline
#Load text generation model(GenAI)
generator = pipeline("text-generation",model="gpt2")

#input prompt
prompt = "Artificial Intelligence in finance will"

#Generate text
result = generator(prompt, max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])